### ISSUE TITLE
nngraph

### ISSUE THREAD

**Issue by skaae** [Kaixhin/nninit#1]
How would you use it for nngraph layers? 
Edit2: It seems to be problem with cudnn layers?

edit: This seems awesome addition to torch :)

**Comment by skaae** [comment]
calcFan should be changed to also recognize cudnn modules. Maybe you should also catch unrecognized layers? 

I can create a PR if you can tell me how to install a module from a local repo. I'm very new to luarocks packages..

``` LUA
local function calcFan(module)
  local typename = module.__typename
  if typename == 'nn.Linear' then
    return module.weight:size(2), module.weight:size(1)
elseif typename == 'nn.TemporalConvolution' or typename == 'cudnn.TemporalConvolution' then
    return module.weight:size(2), module.weight:size(1)
elseif typename == 'nn.SpatialConvolution' or typename == 'cudnn.SpatialConvolution' then
    return module.nInputPlane * module.kW * module.kH, module.nOutputPlane * module.kW * module.kH
elseif typename == 'nn.VolumetricConvolution' or typename == 'cudnn.VolumetricConvolution' then
    return module.nInputPlane * module.kT * module.kW * module.kH, module.nOutputPlane * module.kT * module.kW * module.kH
  end
end
```

**Comment by Kaixhin** [comment]
Thanks for offering to help! I agree that this should have support for `nngraph`. In aebdf8b I added support for `cudnn.SpatialConvolution` and `cudnn.VolumetricConvolution`. `calcFan` now throws an error if it sees an unsupported module - but if you have a better idea on how to deal with this then let's discuss.

I'm still new to `luarocks` as well... At the moment doing `luarocks make rocks/nninit-scm-1.rockspec` seems to work for local testing.

I'll make an issue for proposing an API change too.

**Comment by Kaixhin** [comment]
Actually, I realised that `nngraph` is naturally supported. For example you can change the second line from the [first example](https://github.com/torch/nngraph#two-hidden-layers-mlp) as such:

``` lua
h2 = nninit.biasConstant(nninit.sparse(nn.Linear(10, 1), 0.5), 0)(nn.Tanh()(nninit.normal(nn.Linear(10, 10), 0, 0.3)(nn.Tanh()(h1))))
```

The key is returning the module itself :wink: In this case it's a matter of [function composition](https://en.wikipedia.org/wiki/Function_composition_%28computer_science%29), but I plan to change this to use [method chaining](https://en.wikipedia.org/wiki/Method_chaining) instead (see https://github.com/Kaixhin/nninit/issues/2).
