### ISSUE TITLE
Why isn't "convolution-aware initialization" redundant?

### ISSUE THREAD

**Issue by adityaramesh** [Kaixhin/nninit#11]
Plancherel's theorem implies that orthogonality in the spatial domain is equivalent to orthogonality in the frequency domain. From my understanding, CAI doesn't do anything special in the frequency domain aside from simply initializing the filters of each kernel such that they form an orthonormal set. If my understanding is correct, then vanilla orthogonal initialization should accomplish the same thing, making CAI redundant.

See [this Gist](https://gist.github.com/adityaramesh/0faa3443771e1f051bbd7e382f0d60fa) for a simple demo illustrating my point.

**Comment by Kaixhin** [comment]
This isn't a question for the library, it's a question for the author of the original work. [arXiv](https://arxiv.org/abs/1702.06295) lets you get their email, so I suggest discussing this with them directly. Do post back with your findings though :)

**Comment by iperov** [comment]
@adityaramesh  CAI does orthogonal init in FFT space then do IFFT, but regular orthogonal init does not.
