### ISSUE TITLE
Specification for `eye`

### ISSUE THREAD

**Issue by Kaixhin** [Kaixhin/nninit#4]
The `eye` function is wrong for the convolutional layers. In the 2D case every filter can abide by the specification for `torch.eye`, and the same can be extended for 3D along the diagonal. In 1D perhaps the closest is a vector of 1s? This solution would be the most consistent with `torch.eye`, which is good.

Alternatively, considering that these are convolutions, the identity would be the delta function (i.e. a 1 as close to the middle of a tensor as possible). Asking @bshillingford to clarify what he thinks makes more sense.

**Comment by bshillingford** [comment]
Sorry for the late reply. What I meant was the latter thing you mentioned, but that'd only be sensible when `# input feature maps = # output feature maps`, e.g.:

``` lua
conv = nn.SpatialConvolution(4,4,3,3,1,1,1,1)  -- padding added just so we can compute error below
conv.bias:zero()
conv.weight:zero()
for i=1,4 do
  conv.weight:view(4,4,3,3)[{i,i,2,2}] = 1
end

data = torch.randn(4,10,10)
print((conv:forward(data) - data):abs():mean()) -- should be 0, this is the only reason I used padding
```

A reasonable similar initialization is each output feature map being a randomly selected input feature map (sensible for more outputs than inputs), or more simply a filter that computes the mean (+white noise?) of all input feature maps, something like

``` lua
conv.weight:zero():view(nIn,nOut,kW,kH)[{{},{},ceil(kW/2),ceil(kH/2)}]:fill(1/nIn)
```

Not sure if applying `eye` to the individual filters would give a useful initialization..

**Comment by Kaixhin** [comment]
I've added `addUniform` and `addNormal` with 4a26c65, plus `addConstant` and `mulConstant` with bcede78, which when combined with chaining operations makes the initialisations explicit and more modular. Therefore to recreate your suggestion one could do:

``` lua
conv:wInit('eye'):wInit('mulConstant', 1/conv.nInputPlane):wInit('addNormal', 0, 0.01)
```

Does the delta identity then become a useful building block whilst remaining somewhat consistent with the notion behind `eye`?

**Comment by bshillingford** [comment]
Yes, I think so. Your eye building block is for linear layers as far as I
could tell, and only makes sense for equal numbers of inputs and outputs.
Similarly, you need the same for the delta conv filter.

**Comment by Kaixhin** [comment]
I've updated the README with the above example, and decided to go with including the #inputs normalisation in a36490a since it seems like a more useful case and is still consistent with the idea of identity in terms of preserving input -> output (as opposed to identity for weights).

Thanks for the elegant code example! You may want to check the changes, but hopefully this is now fixed.

**Comment by bshillingford** [comment]
Took a quick look. Looks good.
