### ISSUE TITLE
inconsistencies with nninit.orthogonal

### ISSUE THREAD

**Issue by sniklaus** [Kaixhin/nninit#7]
I am experiencing inconsistencies with the orthogonal initialization. In the example below, both modules have the same number of weights but the latter is significantly faster to initialize.

```
th> nn.SpatialConvolution(100, 100, 3, 3):init('weight', nninit.orthogonal)
nn.SpatialConvolution(100 -> 100, 3x3)
                                                                                  [7.6399s]
th> nn.SpatialConvolution(100, 100, 3, 3).weight:nElement()
90000   
                                                                                  [0.0006s]
----

th> nn.SpatialConvolution(100 * 3 * 3, 100, 1, 1):init('weight', nninit.orthogonal)
nn.SpatialConvolution(900 -> 100, 1x1)
                                                                                  [0.0605s]
th> nn.SpatialConvolution(100 * 3 * 3, 100, 1, 1).weight:nElement()
90000   
                                                                                  [0.0006s]
```

Is this a desired behavior or a bug? The cause of this is that nninit.orthogonal uses fanIn and fanOut to determinethe size of the matrix that is ought to be orthogonalized, and it does not seem to be the right way of doing it.

```
local fanIn = sizes[2]
local fanOut = sizes[1]
for d = 3, #sizes do
    fanIn = fanIn * sizes[d]
    fanOut = fanOut * sizes[d]
end

----

nn.SpatialConvolution(100, 100, 3, 3)
fanIn: 900
fanOut: 900

----

nn.SpatialConvolution(100 * 3 * 3, 100, 1, 1)
fanIn: 900
fanOut: 100
```

Thank you for this very handy library.

**Comment by Kaixhin** [comment]
I believe this is the desired behaviour as it is more to do with making the convolutional filters "orthogonal" than just the number of weights. This library was based on `lasagne.init`, so I suggest having a look at [their code for orthogonal initialisation](https://github.com/Lasagne/Lasagne/blob/master/lasagne/init.py#L327) and seeing if that makes sense.

**Comment by sniklaus** [comment]
Thank you for having a look at this. So they determine the size as follows.

```
flat_shape = (shape[0], np.prod(shape[1:]))
```

My understanding of the shape is that it is the weight matrix. For a convolution, they describe it as a four dimensional matrix.

```
    W : Theano shared variable, expression, numpy array or callable
        Initial value, expression or initializer for the weights.
        These should be a 4D tensor with shape
        ``(num_filters, num_input_channels, filter_rows, filter_columns)``.
        See :func:`lasagne.utils.create_param` for more information.
```

So for the examples I gave, we can compute the `flat_shape` as follows.

```
nn.SpatialConvolution(100, 100, 3, 3)
num_filters: 100
num_input_channels: 100
filter_rows: 3
filter_columns: 3
flat_shape = (shape[0], np.prod(shape[1:])) = (100, 900)

----

nn.SpatialConvolution(100 * 3 * 3, 100, 1, 1)
num_filters: 100
num_input_channels: 100 * 3 * 3
filter_rows: 1
filter_columns: 1
flat_shape = (shape[0], np.prod(shape[1:])) = (100, 900)
```

Please correct me in case I am misinterpreting something.

**Comment by Kaixhin** [comment]
Right you are - thanks for checking. I've removed the `fanOut` calculation, which should make this consistent with Lasagne/speeds up the code a lot!

**Comment by sniklaus** [comment]
Thank you!
