### ISSUE TITLE
luarocks install nninit  Error: No results matching query were found.

### ISSUE THREAD

**Issue by CJHFUTURE** [Kaixhin/nninit#8]
Hi getting this error.
On Macosx

luarocks install nninit

Error: No results matching query were found.

**Comment by Kaixhin** [comment]
Still works fine for me. Do you have an internet connection/is it faulty in any way? Is GitHub down? Have you installed Torch in a non-standard way? If possible try another computer as well.

**Edit:** Closing as not an issue.
